In [1]:
import pandas as pd
df = pd.read_csv(r'C:\Documents\Data analytics\projects\my-data-project\E-COMMERCE-PROJECT\data\raw\Amazon Sale Report.csv')

C:\Users\PC\AppData\Local\Temp\ipykernel_8200\3579508650.py:2: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:\Documents\Data analytics\projects\my-data-project\E-COMMERCE-PROJECT\data\raw\Amazon Sale Report.csv')

In [2]:
df_copy = df.copy()
df_copy.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('-', '_')

In [4]:
df_copy.head()

,index,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,...,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,promotion_ids,b2b,fulfilled_by,unnamed:_22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [3]:
df_copy.drop(columns=['index', 'unnamed:_22'], inplace=True)

In [5]:
df_copy.drop(columns=['ship_country', 'currency', 'ship_postal_code', 'promotion_ids', 'courier_status', 'asin'], inplace=True)

In [6]:
string_cols = df_copy.select_dtypes(include=['object', 'string']).columns
for col in string_cols:
    df_copy[col] = (df_copy[col]
                    .fillna('')
                    .str.strip()
                    .str.lower()
                    .str.replace('-', '_', regex=False)
                    .str.replace(' ', '_', regex=False)
                    .replace('', pd.NA))

In [4]:
correct_data_types = {
    'date': 'datetime64[ns]',
    'status': 'string',
    'fulfilment': 'string',
    'sales_channel': 'string',
    'ship_service_level': 'string',
    'style': 'string',
    'sku': 'string',
    'category': 'string',
    'size': 'string',
    'qty': 'int',
    'amount': 'float',
    'ship_city': 'string',
    'ship_state': 'string',
    'b2b': 'bool',
    'fulfilled_by': 'string',
}
df_copy = df_copy.astype(correct_data_types)
df_copy.dtypes

order_id                      object
date                  datetime64[ns]
status                string[python]
fulfilment            string[python]
sales_channel         string[python]
ship_service_level    string[python]
style                 string[python]
sku                   string[python]
category              string[python]
size                  string[python]
asin                          object
courier_status                object
qty                            int64
currency                      object
amount                       float64
ship_city             string[python]
ship_state            string[python]
ship_postal_code             float64
ship_country                  object
promotion_ids                 object
b2b                             bool
fulfilled_by          string[python]
dtype: object

In [18]:
df_copy.sample(20)

,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,qty,amount,ship_city,ship_state,b2b,fulfilled_by
34987,2022-04-09,shipped,amazon,amazon.in,expedited,jne3405,jne3405_kr_s,kurta,s,1,399.00,thrissur,kerala,False,<NA>
20303,2022-04-18,shipped,amazon,amazon.in,expedited,men5004,men5004_kr_l,kurta,l,1,484.00,kozhikode,kerala,False,<NA>
72382,2022-05-13,cancelled,merchant,amazon.in,standard,jne2086,jne2086_kr_389_m,kurta,m,0,665.71,namakkal,tamil_nadu,False,easy_ship
119321,2022-06-07,shipped,amazon,amazon.in,expedited,set188,set188_kr_np_xxl,set,xxl,1,648.00,hyderabad,telangana,False,<NA>
121402,2022-06-06,shipped___delivered_to_buyer,merchant,amazon.in,standard,jne3797,jne3797_kr_l,western_dress,l,1,735.00,raxaul_bazar,bihar,False,easy_ship
40104,2022-04-06,shipped___delivered_to_buyer,merchant,amazon.in,standard,jne3799,jne3799_kr_l,kurta,l,1,666.00,kolkata,west_bengal,False,easy_ship
6028,2022-04-26,cancelled,merchant,amazon.in,standard,jne3365,jne3365_kr_1052_a_m,kurta,m,0,358.10,enkakkad,kerala,False,easy_ship
111095,2022-06-13,shipped,amazon,amazon.in,expedited,j0332,j0332_dr_xxl,western_dress,xxl,1,828.00,hyderabad,telangana,False,<NA>
112715,2022-06-12,shipped,amazon,amazon.in,expedited,jne3567,jne3567_kr_s,kurta,s,1,399.00,edappal,kerala,False,<NA>
112863,2022-06-11,shipped,amazon,amazon.in,expedited,j0237,j0237_skd_l,set,l,1,1369.00,varkala,kerala,False,<NA>
100414,2022-06-21,shipped,amazon,amazon.in,expedited,jne3504,jne3504_kr_xs,kurta,xs,1,431.00,chennai,tamil_nadu,False,<NA>
64306,2022-05-19,cancelled,amazon,amazon.in,expedited,jne2009,jne2009_kr_310_xs,kurta,xs,0,NaN,pimpri_chinchwad,maharashtra,False,<NA>
81442,2022-05-06,shipped,amazon,amazon.in,expedited,jne3368,jne3368_kr_xxl,kurta,xxl,1,471.00,pune,maharashtra,False,<NA>
113899,2022-06-11,shipped,amazon,amazon.in,expedited,jne3800,jne3800_kr_xxl,western_dress,xxl,1,735.00,surat,gujarat,False,<NA>
15054,2022-04-21,shipped___delivered_to_buyer,merchant,amazon.in,standard,set291,set291_kr_pp_xxl,set,xxl,1,563.00,hassan,karnataka,False,easy_ship
43327,2022-04-04,shipped,amazon,amazon.in,expedited,set348,set348_kr_np_l,set,l,1,958.00,gurugram,haryana,False,<NA>
87919,2022-05-02,cancelled,amazon,amazon.in,expedited,j0127,j0127_skd_s,set,s,0,NaN,kota,rajasthan,False,<NA>
84796,2022-05-04,shipped,amazon,amazon.in,expedited,men5012,men5012_kr_xxxl,kurta,3xl,1,499.00,faridabad,haryana,False,<NA>
23774,2022-04-16,shipped___delivered_to_buyer,merchant,amazon.in,standard,set293,set293_kr_np_m,set,m,1,692.00,ongole,andhra_pradesh,False,easy_ship
39309,2022-04-07,shipped___delivered_to_buyer,merchant,amazon.in,standard,set345,set345_kr_np_xl,set,xl,1,618.00,tiruvallur,tamil_nadu,False,easy_ship

In [7]:
df_copy.dtypes

order_id                      object
date                  datetime64[ns]
status                string[python]
fulfilment            string[python]
sales_channel         string[python]
ship_service_level    string[python]
style                 string[python]
sku                   string[python]
category              string[python]
size                  string[python]
qty                            int64
amount                       float64
ship_city             string[python]
ship_state            string[python]
b2b                             bool
fulfilled_by          string[python]
dtype: object

In [ ]:
#drop

In [8]:
df_copy.drop(columns=['order_id'], inplace=True)

In [9]:
import numpy as np
missingvals = ['N/A', 'None', 'none', 'NONE', 'n/a', '?', 'nan', 'na', 'null', 'Null', 'NULL', '<NA>', 'NA']
df_copy = df_copy.replace(missingvals, np.nan)

In [27]:
df_copy.sample(10)

,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,qty,amount,ship_city,ship_state,b2b,fulfilled_by
43997,2022-04-04,shipped,amazon,amazon.in,expedited,jne3784,jne3784_kr_xl,kurta,xl,1,452.0,thane,maharashtra,False,<NA>
78726,2022-05-07,shipped,amazon,amazon.in,expedited,set345,set345_kr_np_l,set,l,1,613.0,matla,west_bengal,False,<NA>
16685,2022-04-20,shipped,amazon,amazon.in,expedited,set291,set291_kr_pp_m,set,m,1,563.0,navi_mumbai,maharashtra,False,<NA>
85966,2022-05-03,shipped___delivered_to_buyer,merchant,amazon.in,standard,men5006,men5006_kr_m,kurta,m,1,475.0,nagpur,maharashtra,False,easy_ship
127471,2022-06-01,shipped___delivered_to_buyer,merchant,amazon.in,standard,j0157,j0157_dr_xxxl,western_dress,3xl,1,659.0,bhimavaram,andhra_pradesh,False,easy_ship
122140,2022-06-05,shipped___delivered_to_buyer,merchant,amazon.in,standard,jne3160,jne3160_kr_g_xl,kurta,xl,1,729.0,raichur,karnataka,False,easy_ship
10251,2022-04-24,shipped,amazon,amazon.in,expedited,men5032,men5032_kr_l,kurta,l,1,562.0,debagarh,odisha,False,<NA>
116260,2022-06-09,shipped,amazon,amazon.in,expedited,jne3797,jne3797_kr_l,western_dress,l,1,735.0,chennai,tamil_nadu,False,<NA>
24429,2022-04-16,shipped,amazon,amazon.in,expedited,j0230,j0230_skd_m,set,m,1,1112.0,nagpur,maharashtra,False,<NA>
4826,2022-04-27,shipped___delivered_to_buyer,merchant,amazon.in,standard,btm030,btm030_np_xxl,bottom,xxl,1,284.0,cochin,kerala,False,easy_ship

In [10]:
df_cleaned = df_copy.drop_duplicates()

In [13]:
df_cleaned['status'].unique()

<StringArray>
[                    'cancelled',  'shipped___delivered_to_buyer',
                       'shipped',  'shipped___returned_to_seller',
   'shipped___rejected_by_buyer',     'shipped___lost_in_transit',
    'shipped___out_for_delivery', 'shipped___returning_to_seller',
           'shipped___picked_up',                       'pending',
 'pending___waiting_for_pick_up',             'shipped___damaged',
                      'shipping']
Length: 13, dtype: string

In [11]:
df_cleaned['status'] = df_cleaned['status'].str.replace('___', '_')

C:\Users\PC\AppData\Local\Temp\ipykernel_8200\535288302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['status'] = df_cleaned['status'].str.replace('___', '_')

In [15]:
df_cleaned.sample(20)

,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,qty,amount,ship_city,ship_state,b2b,fulfilled_by
88500,2022-05-02,shipped,amazon,amazon.in,expedited,set397,set397_kr_np_xxl,set,xxl,1,1115.00,bhopal,madhya_pradesh,False,<NA>
50313,2022-05-31,shipped,amazon,amazon.in,expedited,nw029,nw029_st_sr_s,set,s,1,455.00,surat,gujarat,False,<NA>
52962,2022-05-28,shipped,amazon,amazon.in,expedited,jne3799,jne3799_kr_xxl,kurta,xxl,1,666.00,chennai,tamil_nadu,False,<NA>
87600,2022-05-02,shipped,amazon,amazon.in,expedited,jne3160,jne3160_kr_g_m,kurta,m,1,685.00,pune,maharashtra,False,<NA>
100297,2022-06-21,cancelled,merchant,amazon.in,standard,j0341,j0341_dr_m,western_dress,m,0,1112.38,pondicherry,puducherry,False,easy_ship
25128,2022-04-15,shipped_delivered_to_buyer,merchant,amazon.in,standard,set248,set248_kr_np_xxxl,set,3xl,1,612.00,bengaluru,karnataka,False,easy_ship
19014,2022-04-19,shipped_delivered_to_buyer,merchant,amazon.in,standard,jne3710,jne3710_dr_xl,western_dress,xl,1,690.00,ahmedabad,gujarat,False,easy_ship
35289,2022-04-09,shipped_delivered_to_buyer,merchant,amazon.in,standard,jne3573,jne3573_kr_s,kurta,s,1,381.00,dombivli_west,maharashtra,False,easy_ship
24321,2022-04-16,shipped,amazon,amazon.in,expedited,jne3568,jne3568_kr_xl,kurta,xl,1,399.00,mumbai,maharashtra,False,<NA>
75321,2022-05-10,shipped_delivered_to_buyer,merchant,amazon.in,standard,set356,set356_kr_np_xxl,set,xxl,1,999.00,ranchi,jharkhand,False,easy_ship
20223,2022-04-18,cancelled,amazon,amazon.in,expedited,j0342,j0342_tp_l,top,l,1,540.00,bengaluru,karnataka,False,<NA>
50233,2022-05-31,cancelled,amazon,amazon.in,expedited,j0126,j0126_skd_xl,set,xl,0,NaN,faridabad,haryana,False,<NA>
43047,2022-04-04,shipped,amazon,amazon.in,expedited,jne3568,jne3568_kr_m,kurta,m,1,449.00,bhubaneswar,odisha,False,<NA>
102809,2022-06-19,shipped_delivered_to_buyer,merchant,amazon.in,standard,jne3391,jne3391_kr_xxl,kurta,xxl,1,419.00,kolkata,west_bengal,False,easy_ship
21831,2022-04-17,shipped_delivered_to_buyer,merchant,amazon.in,standard,j0343,j0343_dr_m,western_dress,m,1,744.00,idukki,kerala,False,easy_ship
5026,2022-04-27,shipped_delivered_to_buyer,merchant,amazon.in,standard,j0004,j0004_skd_xxl,set,xxl,1,1115.00,noida,uttar_pradesh,False,easy_ship
72059,2022-05-13,shipped_delivered_to_buyer,merchant,amazon.in,standard,set397,set397_kr_np_xxl,set,xxl,1,999.00,coimbatore,tamil_nadu,False,easy_ship
65406,2022-05-18,shipped,amazon,amazon.in,expedited,set152,set152_kr_np_xs,set,xs,1,469.00,chandigarh,chandigarh,False,<NA>
17892,2022-04-20,shipped,amazon,amazon.in,expedited,set289,set289_kr_np_xl,set,xl,1,666.00,jabalpur,madhya_pradesh,False,<NA>
85674,2022-05-03,shipped,amazon,amazon.in,expedited,jne3560,jne3560_kr_xxxl,kurta,3xl,1,458.00,silchar,assam,False,<NA>

In [13]:
df_cleaned['ship_state'].unique()

<StringArray>
[      'maharashtra',         'karnataka',        'tamil_nadu',
     'uttar_pradesh',            'punjab',         'telangana',
    'andhra_pradesh',         'rajasthan',             'delhi',
           'haryana',             'assam',         'jharkhand',
      'chhattisgarh',            'odisha',            'kerala',
    'madhya_pradesh',       'west_bengal',          'nagaland',
           'gujarat',       'uttarakhand',             'bihar',
   'jammu_&_kashmir',  'himachal_pradesh', 'arunachal_pradesh',
           'manipur',               'goa',         'meghalaya',
           'tripura',   'dadra_and_nagar',            'sikkim',
                <NA>, 'andaman_&_nicobar',           'mizoram',
       'lakshadweep']
Length: 34, dtype: string

In [12]:
state_mapping = {
    'orissa' : 'odisha',
    'punjab/mohali/zirakpur' : 'punjab',
    'nl' : 'nagaland',
    'rajsthan' : 'rajasthan',
    'rajshthan' : 'rajasthan',
    'up' : 'uttar_pradesh',
    'pb' : 'punjab',
    'ar' : 'arunachal_pradesh',
    'rj' : 'rajasthan',
    'apo' : 'delhi',
    'new_delhi' : 'delhi',
    'chandigarh' : 'punjab',
    'ladakh' : 'jammu_&_kashmir',
    'puducherry' : 'tamil_nadu',
    'pondicherry' : 'tamil_nadu',
    

   
}
df_cleaned['ship_state'] = df_cleaned['ship_state'].replace(state_mapping)

C:\Users\PC\AppData\Local\Temp\ipykernel_8200\1977900792.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['ship_state'] = df_cleaned['ship_state'].replace(state_mapping)

In [14]:
df_cleaned['ship_city'].unique()

<StringArray>
[                    'mumbai',                  'bengaluru',
                'navi_mumbai',                 'puducherry',
                    'chennai',                  'ghaziabad',
                 'chandigarh',                  'hyderabad',
                      'noida',                  'amravati.',
 ...
                  'dombiwali',                   'bangluru',
         'kothapalle,_e.g.dt',               'eroor__kochi',
 'mambakkam,_chingleput_dist',           'new_delhi_110032',
      'vaishali_nagar_nagpur',           'cherukunnu_(p.o)',
  'gulabpura,_distt_bhilwara',      'prayagraj_(allahabad)']
Length: 7276, dtype: string

In [15]:
df_cleaned.drop(columns=['ship_city'], inplace=True)

C:\Users\PC\AppData\Local\Temp\ipykernel_8200\3998914186.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned.drop(columns=['ship_city'], inplace=True)

In [18]:
df_cleaned.sample(10)

,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,qty,amount,ship_state,b2b,fulfilled_by
125023,2022-06-03,shipped,amazon,amazon.in,expedited,j0003,j0003_set_s,set,s,1,664.0,telangana,False,<NA>
94849,2022-06-26,shipped_picked_up,merchant,amazon.in,standard,j0347,j0347_set_xs,set,xs,1,679.0,haryana,False,easy_ship
81458,2022-05-06,shipped,amazon,amazon.in,expedited,sar149,sar149,saree,free,1,756.0,bihar,False,<NA>
121777,2022-06-05,shipped,amazon,amazon.in,expedited,j0002,j0002_skd_xl,set,xl,1,1125.0,karnataka,False,<NA>
57947,2022-05-25,shipped,amazon,amazon.in,expedited,jne3642,jne3642_tp_xl,top,xl,1,321.0,haryana,False,<NA>
76470,2022-05-09,shipped,amazon,amazon.in,expedited,jne3671,jne3671_tu_xxxl,top,3xl,1,625.0,punjab,False,<NA>
111405,2022-06-12,shipped,amazon,amazon.in,expedited,j0005,j0005_dr_xl,western_dress,xl,1,899.0,karnataka,False,<NA>
70098,2022-05-15,shipped_delivered_to_buyer,merchant,amazon.in,standard,nw012,nw012_tp_pj_l,set,l,1,537.0,andhra_pradesh,False,easy_ship
88228,2022-05-02,shipped,amazon,amazon.in,expedited,jne3568,jne3568_kr_xl,kurta,xl,1,399.0,rajasthan,False,<NA>
124573,2022-06-04,shipped,amazon,amazon.in,expedited,j0008,j0008_skd_xs,set,xs,1,1075.0,delhi,False,<NA>

In [20]:
df_cleaned.to_csv(r'C:\Documents\Data analytics\projects\my-data-project\E-COMMERCE-PROJECT\data\processed\amazon_sales_cleaned.csv', index=False)